[2023-06-06T12:46:15.728+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: GetAPIdata_v01.0.first_test manual__2023-06-06T12:46:13.478849+00:00 [queued]>
[2023-06-06T12:46:15.741+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: GetAPIdata_v01.0.first_test manual__2023-06-06T12:46:13.478849+00:00 [queued]>
[2023-06-06T12:46:15.741+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 4
[2023-06-06T12:46:15.762+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): first_test> on 2023-06-06 12:46:13.478849+00:00
[2023-06-06T12:46:15.766+0000] {standard_task_runner.py:57} INFO - Started process 385 to run task
[2023-06-06T12:46:15.770+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'GetAPIdata_v01.0', 'first_test', 'manual__2023-06-06T12:46:13.478849+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/sports/dag_test.py', '--cfg-path', '/tmp/tmp97kfa3od']
[2023-06-06T12:46:15.773+0000] {standard_task_runner.py:85} INFO - Job 3: Subtask first_test
[2023-06-06T12:46:15.844+0000] {task_command.py:410} INFO - Running <TaskInstance: GetAPIdata_v01.0.first_test manual__2023-06-06T12:46:13.478849+00:00 [running]> on host a73ed875b1d0
[2023-06-06T12:46:15.990+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='GetAPIdata_v01.0' AIRFLOW_CTX_TASK_ID='first_test' AIRFLOW_CTX_EXECUTION_DATE='2023-06-06T12:46:13.478849+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-06-06T12:46:13.478849+00:00'
[2023-06-06T12:46:16.984+0000] {logging_mixin.py:149} INFO - Something went wrong! Error: 1 validation error for ScoresDict
scores
  str type expected (type=type_error.str)
[2023-06-06T12:46:16.984+0000] {logging_mixin.py:149} INFO - data={} response_headers={'Date': 'Tue, 06 Jun 2023 12:46:17 GMT', 'Content-Type': 'application/json', 'Content-Length': '1374', 'Connection': 'keep-alive', 'content-encoding': 'gzip', 'Apigw-Requestid': 'GGOYFgPXoAMEa6Q=', 'vary': 'Accept-Encoding', 'X-RateLimit-Requests-Limit': '500', 'X-RateLimit-Requests-Remaining': '442', 'X-RateLimit-Requests-Reset': '2074901', 'Server': 'RapidAPI-1.2.8', 'X-RapidAPI-Version': '1.2.8', 'X-RapidAPI-Region': 'AWS - sa-east-1'}
[2023-06-06T12:46:16.984+0000] {python.py:183} INFO - Done. Returned value was: None
[2023-06-06T12:46:17.000+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=GetAPIdata_v01.0, task_id=first_test, execution_date=20230606T124613, start_date=20230606T124615, end_date=20230606T124617
[2023-06-06T12:46:17.027+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-06-06T12:46:17.056+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
